# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1


workflows:
   heroku_deploy:
     jobs:
       - build
       - heroku/deploy-via-git:
           requires:
             - build
           filters:
             branches:
               only: master

jobs:
  build:
    docker:
      - image: clojure:openjdk-11-tools-deps-slim-buster

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: clojure -A:test
